name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch name if it's not `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (Upgrade to 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Updated from 16 to 18 for sharp compatibility

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Generate static files
      - name: Generate static files
        run: NODE_ENV=production npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist